spring:
  application:
    name: hello-spring-cloud-eureka
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
#    两个false代表开启eureka服务端模式,写默认未true,即客户端模式
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/