spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/heajing007/spring-cloud-config.git
          search-paths: respo
          username: hajahz@qq.com
          password: heajing123456

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/