spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/heajing007/spring-cloud-config.git
          search-paths: respo
          username: hajahz@qq.com
          password: heajing123456

#  配置服务器的默认端口为 8888，如果修改了默认端口，
#  则客户端项目就不能在 application.yml 或 application.properties 中配置
#  spring.cloud.config.uri，必须在 bootstrap.yml 或是 bootstrap.properties 中配置，
#  原因是 bootstrap 开头的配置文件会被优先加载和配置，切记。
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/