spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
#  云配置,取代下方的配置
  cloud:
    config:
      uri: http://localhost:8888
      name: web-admin-feign
      label: master
      profile: prod
#####################
#server:
#  port: 8765
#
#feign:
#  hystrix:
#    enabled: true
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#####################